In [1]:
import numpy as np

In [2]:
person_height=np.array([10,20,30,40,77,88])

In [3]:
person_height

array([10, 20, 30, 40, 77, 88])

In [4]:
person_weight=np.array([10,20,30,40,50,60])

In [5]:
person_weight

array([10, 20, 30, 40, 50, 60])

In [6]:
person_height[0]

10

In [7]:
person_weight[3]

40

In [8]:
mul_dim=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
mul_dim[0]

array([1, 2, 3])

# access index elements

In [10]:
mul_dim[0][1]

2

In [11]:
mul_dim[2,0]

7

In [12]:
mul_dim[:,1]

array([2, 5, 8])

In [13]:
mul_dim[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
mul_dim[:,2]

array([3, 6, 9])