In [240]:
import numpy as np
import torch

In [241]:
a=np.array([1,2,3,4,5])

In [242]:
type(a)

numpy.ndarray

In [243]:
a[2]=10
print(a)

[ 1  2 10  4  5]


In [244]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [245]:
b.shape

(2, 3)

In [246]:
print(b[0,2])

3


# Create an array of all zeros

In [247]:
c = np.zeros((3,3))  
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Create an array of all ones

In [248]:
d = np.ones((4,3))   
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


 # Create a constant array

In [249]:
e = np.full((5,5), 7)
print(e)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [250]:
 # Create a 4X4 identity matrix

In [251]:
d = np.eye(4)       
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Create an array filled with random values

In [252]:
e = np.random.random((3,3)) 
print(e)

[[0.37684841 0.62897359 0.19464253]
 [0.7122146  0.29573283 0.09133192]
 [0.76805442 0.94117019 0.09984027]]


# Data type objects (dtype)

* A data type object (an instance of numpy.dtype class) describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.[For More Details Please Check](https://numpy.org/doc/stable/reference/arrays.dtypes.html)





In [253]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [254]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [255]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


#  Elementwise difference; both produce the array

In [256]:
z=x-y
print(z)
print(type(z))

[[-4. -4.]
 [-4. -4.]]
<class 'numpy.ndarray'>


In [257]:
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


# Elementwise product; both produce the array

In [258]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


# Elementwise division; both produce the array

In [259]:

# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Elementwise square root; produces the array

In [260]:

# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


 # **Important Note**

*  `*` is elementwise multiplication, not matrix multiplication. **We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.** dot is available both as a function in the numpy module and as an instance method of array objects:

``` (9 * 11) + (10 * 12) = 99 + 120 = 219```

In [261]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


**You can also use the @ operator which is equivalent to numpy's dot operator.**

In [262]:
print(v @ w)

219


```c[0][0] = a[0][0] * b[0][0] + a[0][1] * b[1][0]\
        = 1 * 4 + 2 * 2
        = 8```

```c[1][0] = a[1][0] * b[0][0] + a[1][1] * b[1][0]
        = 4 * 4 + 1 * 2
        = 16 + 2
        = 18```

```c[0][1] = a[0][0] * b[0][1] + a[0][1] * b[1][1]
        = 1 * 11 + 2 * 3
        = 11 + 6
        = 17```

```c[1][1] = a[1][0] * b[0][1] + a[1][1] * b[1][1]```
        ```= 4 * 11 + 1 * 3```
        ```= 44 + 3```
        ```= 47```


In [263]:
a = [[1, 2], [4, 1]]  
b = [[4, 11], [2, 3]]  
c=np.dot(a, b)  
c  

array([[ 8, 17],
       [18, 47]])

In [264]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [265]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


> Numpy provides many useful functions for performing computations on arrays; one of the most useful is **`sum`**:

In [266]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1)) 

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [267]:
print(x)


[[1 2]
 [3 4]]


In [268]:
print("transpose\n", x.T)

transpose
 [[1 3]
 [2 4]]


In [269]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


# example of vector operation

In [270]:

x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


* In fact, if  x=(x1,x2,...,xn)  is a row vector then  np.exp(x)  will apply the exponential function to every element of x. The output will thus be:  np.exp(x)=(ex1,ex2,...,exn)

In [271]:
x = np.array([1, 2, 3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


## Introduction to Tensors

A **PyTorch Tensor** is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic **n-dimensional array** to be used for arbitrary **numeric computation**.

The biggest difference between a numpy array and a PyTorch Tensor is that a **PyTorch Tensor can run on either CPU or GPU**. To run operations on the GPU, **just cast the Tensor to a cuda datatype**.


A scalar is **zero-order tensor** or rank zero tensor. A vector is a **one-dimensional** or first order tensor, and a matrix is a **two-dimensional** or second order tensor. 



<div align="center">
<img src="https://drive.google.com/uc?id=1pka-LVyrq_7r0sCm59cvOQofEYAcnO4r" width="550">
</div>

<div align="center">
<img src="https://drive.google.com/uc?id=1zHT5CGzIgpe1aLkdawrllTMn74nYVeAp" width="550">
</div>



A [torch.Tensor](https://pytorch.org/docs/stable/tensors.html) is a **multi-dimensional matrix** containing elements of a **single data type**.

`torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`).

In [272]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [273]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2629, 0.9756, 0.2783],
        [0.6633, 0.2972, 0.4155],
        [0.5341, 0.4030, 0.4315],
        [0.4384, 0.8417, 0.4628],
        [0.1458, 0.7584, 0.9383]])


In [274]:
type(x)

torch.Tensor

In [275]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

# Converting numpy arrays to tensors

In [276]:

np_values = np.array([[1, 2, 3], [4, 5, 6]])

tensor_values = torch.from_numpy(np_values)

print (tensor_values)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [277]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

# The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [278]:

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])



tensor(6)


In [279]:
# Modify a certain element
x[0][1] = 8
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


# Use torch.Tensor.item() to get a Python number from a tensor containing a single value

In [280]:
x = torch.tensor([[1]])
print (x)

tensor([[1]])


In [281]:
print(x.item())

1


In [282]:
x = torch.tensor(2.5)

print(x.item())

2.5


In [283]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


# Tensor addition & subtraction

In [284]:

x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [285]:

print(x)

tensor([[0.1155, 0.7676, 0.8324],
        [0.5395, 0.3511, 0.5068],
        [0.7069, 0.1097, 0.5192],
        [0.8853, 0.3837, 0.6741],
        [0.9131, 0.2052, 0.8537]])


In [286]:

print(y)

tensor([[0.0584, 0.8141, 0.2025],
        [0.0467, 0.3085, 0.5483],
        [0.3207, 0.1005, 0.3950],
        [0.9568, 0.7944, 0.9205],
        [0.1728, 0.5984, 0.5382]])


In [287]:
print(x + y)

tensor([[0.1739, 1.5816, 1.0349],
        [0.5862, 0.6597, 1.0551],
        [1.0276, 0.2102, 0.9142],
        [1.8421, 1.1781, 1.5946],
        [1.0859, 0.8036, 1.3919]])


In [288]:
print(x - y)

tensor([[ 0.0572, -0.0465,  0.6299],
        [ 0.4928,  0.0426, -0.0416],
        [ 0.3863,  0.0093,  0.1243],
        [-0.0715, -0.4107, -0.2463],
        [ 0.7404, -0.3932,  0.3154]])


In [289]:
m=torch.tensor([[1,2,3,4],[5,6,7,8]])
n=torch.tensor([[1,2,3,4],[5,6,7,8]])


In [290]:
m+n

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

# Syntax 2 for Tensor addition & subtraction in PyTorch

In [291]:
print(torch.add(x, y))
print(torch.sub(x, y))

tensor([[0.1739, 1.5816, 1.0349],
        [0.5862, 0.6597, 1.0551],
        [1.0276, 0.2102, 0.9142],
        [1.8421, 1.1781, 1.5946],
        [1.0859, 0.8036, 1.3919]])
tensor([[ 0.0572, -0.0465,  0.6299],
        [ 0.4928,  0.0426, -0.0416],
        [ 0.3863,  0.0093,  0.1243],
        [-0.0715, -0.4107, -0.2463],
        [ 0.7404, -0.3932,  0.3154]])


# Tensor Product & Transpose

In [292]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)

print(mat1)


tensor([[-0.1347,  0.4235,  0.8328],
        [ 1.2167,  0.6766, -0.2158]])


In [293]:
print(mat2)

tensor([[-0.5954,  1.0230, -0.4423],
        [ 0.4278, -0.0112,  1.4343],
        [ 1.4000,  0.6884,  0.9171]])


In [294]:

print(torch.mm(mat1, mat2))

tensor([[ 1.4274,  0.4308,  1.4308],
        [-0.7371,  1.0886,  0.2345]])


In [295]:

print(mat1.t())

tensor([[-0.1347,  1.2167],
        [ 0.4235,  0.6766],
        [ 0.8328, -0.2158]])


In [296]:
# Elementwise multiplication
t = torch.Tensor([[1, 2], [3, 4]])
t.mul(t)

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [297]:

x = torch.rand(5, 3)

print('Tensor shape:', x.shape)   # t.size() gives the same
print('Number of dimensions:', x.dim())
print('Tensor type:', x.type())

Tensor shape: torch.Size([5, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


In [298]:
# Slicing
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])







In [299]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [300]:
# Every row, only the last column
print(t[:, -1])

tensor([3., 6., 9.])


In [307]:
# First 2 rows, all columns
print(t[: 2])

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [310]:
# Lower right most corner
print(t[-1:,-1])

tensor([9.])


In [311]:
t[:,2]

tensor([3., 6., 9.])