In [57]:
import numpy as np

In [58]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [59]:
x.ndim

2

# flattens the datasets

In [60]:
y=x.ravel()

In [61]:
y.ndim

1

In [62]:
y.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
y.resize(2,5)

In [64]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
np.hsplit(y,5)

[array([[1],
        [6]]), array([[2],
        [7]]), array([[3],
        [8]]), array([[4],
        [9]]), array([[ 5],
        [10]])]

In [66]:
np.hstack((x,y))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [67]:
z=np.array([[1,2,3],[4,5,6]])

In [68]:
v=np.zeros((3,3))

In [69]:
print(v)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [70]:
c=np.ones((3,3))

In [71]:
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [72]:
e=np.empty((4,4))

In [73]:
e

array([[4.2718133e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [74]:
f=np.arange(1,10)

In [75]:
f.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
lin_sp=np.linspace(1,10,6)#(start,end,how many numbers u want)

In [77]:
print(lin_sp)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [78]:
one_dim=np.array([1,2,3,4,5,6,7,8,9])

In [79]:
one_dim.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
thr_dim=np.arange(24).reshape(4,3,2)

In [81]:
thr_dim

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])