In [1]:
import numpy as np
import random

## Creating Copies of Arrays

In [2]:
x=np.random.randint(2,20,size=(5,5))

In [3]:
print(x)

[[ 2 13  3  3  9]
 [16  7  8 14  3]
 [12  7  4  4  5]
 [12  7 14  7 15]
 [11 13 15 12 10]]


In [4]:
x1=x[: 2 ,:4].copy()

In [5]:
x1

array([[ 2, 13,  3,  3],
       [16,  7,  8, 14]])

## Slice (start,stop,step)

In [6]:
a=np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
s=slice(2,10,2)
print(s)

slice(2, 10, 2)


In [9]:
print(a[s])

[2 4 6 8]


In [11]:
b=a[2 : ]
print(b)

[2 3 4 5 6 7 8 9]


In [12]:
np.random.seed(10)

In [14]:
data=np.random.randint(2,20,size=(5,5))

In [15]:
print(data)

[[11  6 17  2 19]
 [18 19 10 11  2]
 [12 10  6 18  6]
 [17 13 13  3 10]
 [ 6 16 19 15  7]]


In [17]:
data[0][4]

19

In [19]:
data[: 2,0 : 3]

array([[11,  6, 17],
       [18, 19, 10]])

## Accessing first row

In [20]:
data[: 1]

array([[11,  6, 17,  2, 19]])

In [22]:
data[0 : 1]

array([[11,  6, 17,  2, 19]])

## access all columns

In [26]:
data[:,0 : 5 ]

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [27]:
data[: , 0 : 3]

array([[11,  6, 17],
       [18, 19, 10],
       [12, 10,  6],
       [17, 13, 13],
       [ 6, 16, 19]])

In [28]:
data.shape

(5, 5)

In [29]:
data.size

25

In [31]:
data.ndim

2

In [34]:
b=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [39]:
b.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [40]:
b.shape

(2, 5)

In [41]:
b.size

10

In [42]:
b.ndim

2

In [53]:
g=np.arange(10).reshape((1,-1))

In [52]:
print(g)

[[0 1 2 3 4 5 6 7 8 9]]


In [54]:
g.shape

(1, 10)

## splitting

In [55]:
x=[1,2,3,4,5,5,6,6,7,8,9]

In [58]:
x1=np.split(x,[1,2])

In [59]:
x1

[array([1]), array([2]), array([3, 4, 5, 5, 6, 6, 7, 8, 9])]

## hsplit

In [63]:
data

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6],
       [17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

In [64]:
h=[1,2,3,4,5,6,7,8,9]
d,e=np.hsplit(data,[4])

In [65]:
d

array([[11,  6, 17,  2],
       [18, 19, 10, 11],
       [12, 10,  6, 18],
       [17, 13, 13,  3],
       [ 6, 16, 19, 15]])

In [66]:
e

array([[19],
       [ 2],
       [ 6],
       [10],
       [ 7]])

## vsplit

In [67]:
h,j=np.vsplit(data,[3])

In [68]:
h

array([[11,  6, 17,  2, 19],
       [18, 19, 10, 11,  2],
       [12, 10,  6, 18,  6]])

In [69]:
j

array([[17, 13, 13,  3, 10],
       [ 6, 16, 19, 15,  7]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=eb3a9c3a-01de-4ac2-99e0-213c14b1ce40' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>