In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4])

In [3]:
n2=np.array([2,3,4,5])

# numpy addition

In [4]:
np.sum([n1,n2],axis=0)

array([3, 5, 7, 9])

In [5]:
np.sum([n1,n2],axis=1)

array([10, 14])

# basic addition,substraction,multiplication,division

In [6]:
n3=np.array([1,2,3,4,5,6])

In [7]:
n4=n3+1

In [8]:
n4

array([2, 3, 4, 5, 6, 7])

In [9]:
n5=n3-1

In [10]:
n5

array([0, 1, 2, 3, 4, 5])

In [11]:
n6=n3*5

In [12]:
n6

array([ 5, 10, 15, 20, 25, 30])

In [13]:
n7=n3/3

In [14]:
n7

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

# mean,medin,standard  deviation

In [15]:
np.mean(n6)

17.5

In [16]:
np.median(n6)

17.5

In [17]:
np.std(n6)

8.539125638299666

In [18]:
n8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
n8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
n8[0]

array([1, 2, 3, 4])

In [21]:
n8[: ,2]

array([ 3,  7, 11])

In [22]:
n8[:,3]

array([ 4,  8, 12])

In [23]:
n9=np.transpose(n8)

In [24]:
n9

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [25]:
n10=np.array([[1,2,34],[6,7,8],[1,2,3]])

In [26]:
n10

array([[ 1,  2, 34],
       [ 6,  7,  8],
       [ 1,  2,  3]])

In [27]:
n11=np.array([[1,2,34],[6,7,8],[1,2,3]])

In [28]:
n11

array([[ 1,  2, 34],
       [ 6,  7,  8],
       [ 1,  2,  3]])

In [29]:
n10.dot(n11)

array([[ 47,  84, 152],
       [ 56,  77, 284],
       [ 16,  22,  59]])

In [30]:
np.save("test",n11)

In [32]:
np.load("test.npy")

array([[ 1,  2, 34],
       [ 6,  7,  8],
       [ 1,  2,  3]])