In [1]:
import numpy as np

In [2]:
n0=np.array([1,2,3,4,5])

In [3]:
type(n0)

numpy.ndarray

In [4]:
n0.ndim

1

# multi dimension

In [5]:
n1=np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [6]:
type(n1)

numpy.ndarray

In [7]:
n1.ndim

2

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((3,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [10]:
n2=np.arange(10,20,2)

In [11]:
n2

array([10, 12, 14, 16, 18])

In [12]:
n2=np.arange(10,100,6)

In [13]:
n2

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94])

In [14]:
n3=np.random.randint(1,100,10)#(start, stop, how many value u wants)

In [15]:
n3

array([20, 97, 31, 16, 87, 48, 46, 14, 42, 33])

In [16]:
n4=np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
n4.shape

(2, 4)

In [18]:
n4.shape=(4,2)

In [19]:
n4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# vstack

In [20]:
n5=np.array([1,2,3,4])
n6=np.array([5,6,7,8])

In [21]:
np.vstack((n5,n6))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# hstack

In [22]:
np.hstack((n5,n6))

array([1, 2, 3, 4, 5, 6, 7, 8])

# column_stack

In [24]:
np.column_stack((n5,n6))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
n7=np.array([1,2,3,4,10,20,30,40])
n8=np.array([5,6,7,8,30,40,50,60])

In [30]:
np.intersect1d(n7,n8)

array([30, 40])

In [31]:
np.setdiff1d(n7,n8)

array([ 1,  2,  3,  4, 10, 20])