In [ ]:
import numpy as np

In [ ]:
a=np.empty(shape=(3,3))

In [ ]:
print(a)

[[2.19865299e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 2.31297541e-312 1.53235071e-047]
 [3.21430503e-057 5.49416901e-090 9.28206930e-072]]


In [ ]:
b=np.empty(shape=(3,3),dtype="int")

In [ ]:
b

[[           44501232                  36                   0]
 [                  0        468151435264 3906421002484540006]
 [3761681274641135917 3271410164358264673 3544445495855886896]]


# empty like

In [14]:
n=([1,2,3],[4,5,6])

In [15]:
np.empty_like(n)

array([[47171696,        0,        0],
       [       0,        0,        0]])

# np.eye

In [16]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [22]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# np.ones

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,2,2), dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
v=np.ones((3,2,4), dtype=int)

In [39]:
v

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
v.ndim

3

# ones_like

In [35]:
x = np.arange(6)

In [36]:
x = x.reshape((2, 3))

In [37]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

# np.zeros

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
k=np.zeros((3,3,1))

In [46]:
k

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [47]:
k.ndim

3

# np.zeros_like

In [48]:
x = np.arange(6)
x = x.reshape((2, 3))

In [49]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

# np.full()

In [51]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [52]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

# np.full_like

In [53]:
x = np.arange(6, dtype=int)

In [54]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [59]:
y = np.zeros([2, 2, 3], dtype=int)
np.full_like(y, [0, 0,25])

array([[[ 0,  0, 25],
        [ 0,  0, 25]],

       [[ 0,  0, 25],
        [ 0,  0, 25]]])

In [61]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [62]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [63]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [64]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [65]:
np.linspace(2.0, 3.0, num=5, retstep=False)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [66]:
np.random.rand(10)

array([0.8578173 , 0.69028902, 0.9574373 , 0.61897442, 0.98585536,
       0.98641569, 0.85858836, 0.16167747, 0.89738583, 0.43810021])

In [67]:
np.random.rand(10,2,5)

array([[[0.67043764, 0.19298555, 0.60107323, 0.69639052, 0.13157152],
        [0.11278062, 0.7628146 , 0.6074757 , 0.25785924, 0.5875275 ]],

       [[0.36406614, 0.53225642, 0.80948864, 0.12882605, 0.84630538],
        [0.51508535, 0.05211818, 0.66063927, 0.13097836, 0.90637576]],

       [[0.80139938, 0.61074037, 0.23005334, 0.58543381, 0.79931446],
        [0.37976073, 0.52614635, 0.18238832, 0.61321687, 0.24006223]],

       [[0.18780401, 0.60642843, 0.96431422, 0.76446491, 0.96387774],
        [0.65768865, 0.65568318, 0.61886691, 0.19486743, 0.56506265]],

       [[0.52144376, 0.08378216, 0.80409916, 0.78451703, 0.32411248],
        [0.07520478, 0.85334686, 0.44904137, 0.07682109, 0.22986905]],

       [[0.29524008, 0.71750341, 0.53277918, 0.4903097 , 0.55500627],
        [0.79974558, 0.67183643, 0.9809947 , 0.3248822 , 0.13154426]],

       [[0.87319588, 0.36301106, 0.99237379, 0.74481884, 0.69561486],
        [0.10440383, 0.00613056, 0.38292499, 0.85081585, 0.11144083]],

      

In [69]:
np.random.randn(3,3)

array([[ 0.45498861, -0.81468981,  0.1067899 ],
       [ 1.19273512, -0.90570922, -0.67090214],
       [-0.8283083 , -0.32398939,  0.15351457]])

In [72]:
np.random.randint(5, size=(2, 4))

array([[2, 0, 1, 3],
       [0, 3, 3, 4]])