# Numpy

* NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays.In numpy dimensions are called as axes.

# 	Why do we need NumPy? [when python lists are already there]

**we cannot perform operations on all the elements of two list directly.**
* For example, we cannot multiply two lists directly we will have to do it element wise. 
* This is where the role of NumPy comes into play.


In [1]:
import numpy as np
import torch

In [2]:
list1 = [1, 2, 3, 4, 5, 6] 
list2 = [10, 9, 8, 7, 6, 5] 

In [3]:
a1 = np.array(list1)
print(a1)

[1 2 3 4 5 6]


In [4]:
type(a1)

numpy.ndarray

# Convert list2 into a NumPy array 

In [5]:
a2 = np.array(list2) 
print(a1*a2)

[10 18 24 28 30 30]


In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [7]:
print(a.dtype)

int64


In [8]:
print(a.ndim)

1


In [9]:
print(a.shape)

(6,)


In [10]:
a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


* In PyTorch, the attribute to get the number of dimensions of a tensor is .dim(), not .ndim(). This is different from NumPy, which uses the .ndim attribute to get the number of dimensions of an array.

* Therefore, when working with PyTorch tensors, you should use .dim() to get the number of dimensions of a tensor

In [11]:


# Create a 2D tensor with shape (5, 3)
x = torch.rand(5, 3)

# Get the shape and number of dimensions of the tensor
print('Tensor shape:', x.shape)
print('Number of dimensions:', x.dim())


Tensor shape: torch.Size([5, 3])
Number of dimensions: 2


In [12]:
a = np.empty((4,4))
print(a)

[[5.43742721e-316 0.00000000e+000 6.20422629e+223 2.19995456e-152]
 [1.17072865e+214 2.63553806e+092 6.29201311e+233 5.07586646e+058]
 [1.66205086e+150 7.68755624e+170 4.65660587e+164 1.00054848e-095]
 [3.22579210e+031 1.66205074e+150 1.30488965e+180 9.10699859e-308]]


In [13]:
b = np.ones_like(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
print(np.linspace(0, 10, 5))


[ 0.   2.5  5.   7.5 10. ]


In [15]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [16]:
a = np.arange(6)  
print(a, "np.arange")

[0 1 2 3 4 5] np.arange


### Both range and arange are functions in Python and NumPy, respectively, that can be used to generate a sequence of numbers. However, there are some differences between the two functions.

### In Python, the range function is a built-in function that generates a sequence of integers. The function takes up to three arguments: start, stop, and step, where start is the starting value of the sequence (default is 0), stop is the stopping value of the sequence (not included in the sequence), and step is the step size between values (default is 1). Here's an example:

In [17]:
# Generate a sequence of integers from 0 to 9
seq = range(10)

# Print the sequence
print(list(seq))  # Output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### In NumPy, the arange function is a function that generates a sequence of numbers. The function takes up to three arguments: start, stop, and step, where start is the starting value of the sequence (default is 0), stop is the stopping value of the sequence (not included in the sequence), and step is the step size between values (default is 1). However, unlike range, arange can generate sequences of non-integer values. Here's an 

In [18]:


# Generate a sequence of floats from 0 to 9
seq = np.arange(0, 10, 0.8)

# Print the sequence
print(seq)  # Output: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


[0.  0.8 1.6 2.4 3.2 4.  4.8 5.6 6.4 7.2 8.  8.8 9.6]


In [19]:
b = np.arange(12).reshape(4,3) 
print("np.arange(12).reshape(4,3)")
print(b)

np.arange(12).reshape(4,3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Indexing using index arrays

In [20]:
print(b.sum(axis=1))  

[ 3 12 21 30]


In [21]:
print(b.min(axis=1)) 

[0 3 6 9]


In [22]:
a=np.array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a[-1])

729


In [23]:
print(a[2:5])

[ 8 27 64]


In [24]:
 a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)

[-1000     1 -1000    27 -1000   125   216   343   512   729]


In [25]:
print(a[ : :-1]) 

[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [26]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]])

In [27]:

print("Vertical stacking:\n", np.vstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
# horizontal stacking 
print("Horizontal stacking:\n", np.hstack((a, b))) 

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [29]:
print(a)

[[1 2]
 [3 4]]


# stacking columns 

In [30]:
c = [5, 6] 
  

print("Column stacking:\n", np.column_stack((a, c)))

Column stacking:
 [[1 2 5]
 [3 4 6]]


In [31]:
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
print(a)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


# horizontal splitting 

In [32]:
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


# vertical splitting

In [33]:
 print("Splitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [34]:
a = np.arange(20, 10, -1)  
print("sequential array with a negative step: ",a)

sequential array with a negative step:  [20 19 18 17 16 15 14 13 12 11]


# Indexes are specified inside the np.array method.

In [35]:
newnp = a[np.array([4, 3, 1, 2 ])] 
print(a)
print("Elements: ",newnp)

[20 19 18 17 16 15 14 13 12 11]
Elements:  [16 17 19 18]


In [36]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
  
# Index values can be negative. 
arr = a[np.array([1, 3, -3])]
print("Elements: ", arr)

Elements:  [2 4 7]


In [37]:
a = np.arange(20) 
print(a) 
 
  


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [38]:
  
# a[start:stop:step] 
print(a[-8:17:1]) 

[12 13 14 15 16]


In [39]:
# The : operator means all elements till the end. 
print(a[10:])

[10 11 12 13 14 15 16 17 18 19]


In [40]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])


# single row with 0 index column value

In [41]:
print(a[:, 0]) 


[1 4 7]


In [42]:
print(a[:, 1])


[2 5 8]


In [43]:
print(a[:, 2])

[3 6 9]


In [44]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# a[row, column]

In [45]:
print(a[0:2, 1:3]) 
print(a[0:2, 0:2])

[[2 3]
 [5 6]]
[[1 2]
 [4 5]]


In [46]:
np.random.seed(10)
vv = np.random.random((5, 4))
print(vv)


[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]
 [0.72175532 0.29187607 0.91777412 0.71457578]]


In [47]:

print(vv[2:5, 1:2])


[[0.08833981]
 [0.51219226]
 [0.29187607]]


In [48]:
print(vv[2:5, 1])


[0.08833981 0.51219226 0.29187607]


In [49]:
print(vv[2:-1, :])

[[0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [50]:
a = np.array([[1 ,2 ],
              [3 ,4 ],
              [5 ,6 ]]) 

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(a[[0 ,1 ,2 ]])


[[1 2]
 [3 4]
 [5 6]]


In [52]:
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [53]:
b = np.array([[5, 5],
              [15, 5],
              [16, 4]]) 

sumrow = b.sum(1) 
print(sumrow)
print(b[sumrow%10==0])

[10 20 20]
[[ 5  5]
 [15  5]
 [16  4]]
